# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Workflow for build, test and deploy to Kimsufi server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
        
permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install streamlit pandas
        if [ -f tools_app/requirements.txt ]; then pip install -r tools_app/requirements.txt; fi
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r is-tools.zip tools_app
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ns36460.ip-87-98-218.eu
        username: ubuntu
        key: ${{ secrets.KS_PRIVATE_PEM }}
        source: "is-tools.zip"
        target: /home/ubuntu/docker
    - name: Unzip package
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ns36460.ip-87-98-218.eu
        username: ubuntu
        key: ${{ secrets.KS_PRIVATE_PEM }}
        script: |
          cd docker && unzip -o is-tools.zip    
